### ISSUE TITLE
Week1/day1/ex6 - namedOptionalSum

### ISSUE THREAD

**Issue by jotapero** [01-edu/Branch-Mobile#2]
There appears to be a problem with the test cases, if a student were to bruteforce his way through the exercise then there's a solution that passes the tests but prints out incorrect outputs:

```dart
namedOptionalSum ({int? first, int? second, int? third}) {
    var sum = 0;
    if (first != null && second != null && third != null) {
        sum = first + second + third;
    };
    if (first == null && second != null && third != null) {
        sum = second + third;
    };
    if (second == null && first != null && third != null) {
        sum = first + third;
    };
    if (first == null && second == null && third != null) {
        sum = third;
    };

    return sum;
}
``` 

So with this codes all tests pass. However if we were to try this out with these values as parameters, the value should be '2' instead of '0' (which it's what it prints. 

```dart
void main() {
  var res = namedOptionalSum(first: null,second: 2,third: null);
  print(res); 
}
```

**Comment by sakenism** [comment]
You are right, I added more tests to cover all the outcomes

**Comment by jotapero** [comment]
Thank you, it is fixed and working
